// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG831lHQgp9jaiOc0XR-xjxGWgt7XVYl4',
    appId: '1:83056440762:web:491e04223df64b685ed983',
    messagingSenderId: '83056440762',
    projectId: 'liveasy-b7395',
    authDomain: 'liveasy-b7395.firebaseapp.com',
    storageBucket: 'liveasy-b7395.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALj7uopbB9cNYuVMPEWOylqjRLhND9AMQ',
    appId: '1:83056440762:android:10d84897632e7a785ed983',
    messagingSenderId: '83056440762',
    projectId: 'liveasy-b7395',
    storageBucket: 'liveasy-b7395.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKmznwj5Uz6aknSCd__QexKPPrXVeC1-c',
    appId: '1:83056440762:ios:122d9a3ebde795ca5ed983',
    messagingSenderId: '83056440762',
    projectId: 'liveasy-b7395',
    storageBucket: 'liveasy-b7395.appspot.com',
    iosBundleId: 'com.example.liveasyAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKmznwj5Uz6aknSCd__QexKPPrXVeC1-c',
    appId: '1:83056440762:ios:8920bb269f41e4655ed983',
    messagingSenderId: '83056440762',
    projectId: 'liveasy-b7395',
    storageBucket: 'liveasy-b7395.appspot.com',
    iosBundleId: 'com.example.liveasyAssignment.RunnerTests',
  );
}
